import { Command } from 'commander';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

export const goalsCommand = new Command('goals')
  .description('Manage goals.json and auto-generate GOALS.md for agents');

// cortextos goals generate-md --agent <name> --org <org>
goalsCommand
  .command('generate-md')
  .description('Regenerate GOALS.md from goals.json for an agent')
  .requiredOption('--agent <name>', 'Agent name')
  .requiredOption('--org <org>', 'Org name')
  .action((options: { agent: string; org: string }) => {
    const frameworkRoot = process.env.CTX_FRAMEWORK_ROOT || process.cwd();

    if (!/^[A-Za-z0-9_-]+$/.test(options.agent) || !/^[A-Za-z0-9_-]+$/.test(options.org)) {
      process.stderr.write('Error: agent and org must be alphanumeric/dash/underscore only\n');
      process.exit(1);
    }

    const agentDir = join(frameworkRoot, 'orgs', options.org, 'agents', options.agent);
    const goalsJsonPath = join(agentDir, 'goals.json');
    const goalsMdPath = join(agentDir, 'GOALS.md');

    if (!existsSync(goalsJsonPath)) {
      process.stderr.write(`goals.json not found at ${goalsJsonPath}\n`);
      process.exit(1);
    }

    let data: Record<string, unknown>;
    try {
      data = JSON.parse(readFileSync(goalsJsonPath, 'utf-8'));
    } catch {
      process.stderr.write(`Failed to parse goals.json for ${options.agent}\n`);
      process.exit(1);
    }

    const goals = Array.isArray(data.goals)
      ? (data.goals as Array<string | { id?: string; title: string; status?: string; priority?: string }>)
      : [];
    const focus = typeof data.focus === 'string' ? data.focus : '';
    const bottleneck = typeof data.bottleneck === 'string' ? data.bottleneck : '';
    const updatedAt = typeof data.updated_at === 'string' ? data.updated_at : new Date().toISOString();
    const updatedBy = typeof data.updated_by === 'string' ? data.updated_by : '';

    const lines: string[] = [
      '# Goals',
      '',
      '> Auto-generated from goals.json. Do not edit this file directly.',
      `> To regenerate: \`cortextos goals generate-md --agent ${options.agent} --org ${options.org}\``,
      '',
      '## Focus',
      focus || '(not set — check with your orchestrator)',
      '',
      '## Goals',
    ];

    if (goals.length === 0) {
      lines.push('(none set — message your orchestrator to request today\'s goals)');
    } else {
      // Object-form goals carry id / status / priority alongside the title, and
      // this renderer used to emit ONLY the title. A goal that had been closed
      // therefore rendered identically to an active one — braindump's g3 read as
      // indistinguishable from two live goals for as long as it was closed.
      // Status leads the line so the difference is visible at a glance rather
      // than requiring the reader to open goals.json to find out.
      goals.forEach((g, i) => {
        if (typeof g === 'string') {
          lines.push(`${i + 1}. ${g}`);
          return;
        }
        const o = g as { id?: string; title: string; status?: string; priority?: string };
        const id = o.id ? `[${o.id}] ` : '';
        const status = o.status ? `**${o.status.toUpperCase()}** — ` : '';
        // Label the priority: a bare `(1)` sits next to the list's own `1.` and reads as a duplicate.
        const priority = o.priority ? ` _(p${o.priority})_` : '';
        lines.push(`${i + 1}. ${id}${status}${o.title}${priority}`);
      });
    }

    lines.push(
      '',
      '## Bottleneck',
      bottleneck || '(none)',
      '',
      '## Updated',
      updatedBy ? `${updatedAt} (by ${updatedBy})` : updatedAt,
      '',
    );

    writeFileSync(goalsMdPath, lines.join('\n'), 'utf-8');
    console.log(`Generated GOALS.md for ${options.agent}`);
  });
