#!/usr/bin/env bash
# NT8 Strategy Restore Card
# Run after any NT8 recompile/assembly mismatch event to get the rebuild checklist.
# Queries strategy_states for last-known active config + static parameter card.

set -u

DB="postgresql://orbfutures:orbfutures@127.0.0.1/orbfutures_dashboard"

echo "======================================================================"
echo "  NT8 STRATEGY RESTORE CARD — $(TZ=America/Chicago date '+%Y-%m-%d %I:%M %p CT')"
echo "======================================================================"
echo ""

# ── Section 1: Last-known active strategies (from DB) ──────────────────────
echo "SECTION 1: LAST ACTIVE STRATEGIES (pre-incident snapshot)"
echo "──────────────────────────────────────────────────────────"
psql "$DB" -t -A -c "
SELECT
  account_name,
  strategy_name,
  state,
  TO_CHAR(last_seen, 'YYYY-MM-DD HH24:MI UTC') AS last_seen
FROM (
  SELECT DISTINCT ON (account_name, strategy_name)
    account_name, strategy_name, state, last_seen
  FROM strategy_states
  ORDER BY account_name, strategy_name, last_seen DESC
) s
WHERE last_seen > NOW() - INTERVAL '7 days'
ORDER BY account_name, strategy_name;" 2>/dev/null | awk -F'|' '{printf "  %-36s %-30s %-8s %s\n",$1,$2,$3,$4}' || echo "(DB unavailable)"

echo ""

# ── Section 2: H137 Gated Pilot — full parameter card ─────────────────────
echo "SECTION 2: H137 PARAMETER CARD (GATED — VERIFY BEFORE ADDING)"
echo "──────────────────────────────────────────────────────────────"
cat <<'CARD'
Strategy:   H137_BilateralBreakout
Account:    PAAPEX4333770000017  (Apex $50K PA, funded)
Terminal:   HolyGrail (NT8 Windows VPS)
Instrument: MES (Micro E-Mini S&P 500) — current front month
Qty:        1 contract  ← GATED PILOT CONFIG. DO NOT change to 2+ without fable-reviewer approval.
Signal:     9:30-10:30 ET window (OnBarClose, 5-min bars)
Stops:      Dynamic (vol-adjusted). See BrainExecutor.cs v1.2.0 for exact formula.

Required checks BEFORE adding strategy to NT8 chart:
  [ ] MonkeyAttackMonitor is running (strategy_states updating every ~1 min)
  [ ] Account PAAPEX4333770000017 shows in NT8 account list
  [ ] No other strategies assigned to PAAPEX4333770000017 (one-account, one-strategy rule)
  [ ] Contracts parameter = 1
  [ ] Correct instrument (MES, current front month — check expiry)
CARD

echo ""

# ── Section 3: BrainExecutor accounts ─────────────────────────────────────
echo "SECTION 3: BRAINEXECUTOR MAP (Vincere terminal)"
echo "──────────────────────────────────────────────────────────────"
cat <<'CARD'
BrainExecutor v1.2.0-2026-07-10 (current, do not update without chief approval)
Sim account: Sim101 (always re-add first for sanity check)
Live:        MFFUEVFLX450774017 (MFF funded)

After recompile — re-add BrainExecutor to Sim101 first, verify heartbeat in strategy_states,
THEN add to live accounts.
CARD

echo ""

# ── Section 4: Assembly mismatch runbook ───────────────────────────────────
echo "SECTION 4: ASSEMBLY MISMATCH RUNBOOK"
echo "──────────────────────────────────────────────────────────────"
cat <<'RUNBOOK'
Symptoms:
  - "Unable to restore strategy" on NT8 startup
  - strategy_states goes dark (last_seen stops updating)
  - All strategies listed as (unknown type) in NT8 Control Center

Root cause:
  NT8 recompiled its custom assemblies DLL. Strategy instances are tied to the
  compiled assembly fingerprint — any recompile invalidates ALL saved strategy refs.

What triggers a recompile:
  - NT8 auto-update downloaded and installed new version
  - Any .cs file in Documents\NinjaTrader 8\bin\Custom\ was modified/touched
  - NT8 restarted after a crash without a clean shutdown sequence
  - Manual "Compile" in NT8 Control Center

Prevention:
  1. NEVER edit .cs files while NT8 strategies are running on live accounts
  2. Disable NT8 auto-update OR review update notes before allowing install
  3. Always use File → Close before restarting NT8 (clean workspace save)
  4. After any code change: re-add ALL strategies to charts before leaving terminal

Recovery sequence (after recompile):
  1. Open NT8 Control Center → confirm Compile succeeded (no errors)
  2. Run this restore card: bash nt8-restore-card.sh
  3. Re-add strategies to charts using parameter card above
  4. Verify MonkeyAttackMonitor shows fresh entries in strategy_states within 2 min
  5. Send Telegram to devops if recovery complete: pipeline is live again
RUNBOOK

echo ""
echo "======================================================================"
echo "  Generated by nt8-restore-card.sh | Devops agent"
echo "======================================================================"
